# Site settings
title: Gray's Blog
name: Gray's Blog
email: wxc422@mail.ustc.edu.cn
description: > # this means to ignore newlines until "baseurl:"
    我的博客，欢迎光临！
    Hi! I'm Gray, a master candidate in ustc. It's my blog and posts here are works or readings I do recently.
baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "http://wuxichen.github.io" # the base hostname & protocol for your site
safe: false

# twitter_username: jekyllrb
github:  https://github.com/wuxichen
weibo: http://weibo.com/xgray


# Build settings
markdown: redcarpet
highlighter: pygments
