# Site settings
title: Gray's Blog
name: Gray's Blog
email: wxc422@mail.ustc.edu.cn
description: > # this means to ignore newlines until "baseurl:"
    这里是一位准程序员的博客，我将在这里记录近期工作以及编程相关的读书笔记
baseurl: "/Myblog" # the subpath of your site, e.g. /blog/
url: "http://wuxichen.github.io" # the base hostname & protocol for your site
safe: false

# twitter_username: jekyllrb
github:  https://github.com/wuxichen
weibo: http://weibo.com/xgray


# Build settings
markdown: redcarpet
highlighter: pygments

# Global Variables
backup: 备忘速查
reading: 读书笔记
htmlcss: 前端开发
timeseries: 时间序列分析
php: PHP